### ISSUE TITLE
mattermost 5.12 bot accounts channel messages

### ISSUE THREAD

**Issue by Celforyon** [attzonko/mmpy_bot#109]
Mattermost 5.12 has recently been released, including [Bot Accounts](https://docs.mattermost.com/developer/bot-accounts.html).

short version:
- it would be nice to make mmpy_bot fully compatible with bot accounts.

longer version:
I managed to configure mmpy_bot to use a bot account, using the token instead of the password, and it connects and answers **direct** messages.

However, in another channel where the bot *can* talk, it does not answer to messages including a mention (e.g. `@bot`). I suspect that it could be related to the impossibility to really "add to channel" the bot in the Mattermost interface.

**Comment by elixx** [comment]
Is there a way to convert a bot user back into a regular user?

I am impacted by this.

**Comment by attzonko** [comment]
Ok I have read through the documentation on bot accounts. One thing sticks out at me:
```
Bot accounts are just like user accounts, except they:

- Cannot be logged into.
```

The whole premise off `mmpy_bot` is that it logs-in as a "normal" user and can be added to channels and interacted with just like any other user. I have not found any use case described where these new "bot accounts" can listen to and respond to messages. I could not even get direct messages working, how did you do it @Celforyon?

@elixx As far as I read there was no way mentioned to revert that conversion. You can just try to delete the bot account and and create the original account from the command line.

I have sent in a question about this to the Mattermost developers, will keep you posted.

**Comment by Celforyon** [comment]
I nearly did nothing. I used as usually my mmbot Docker image ([celforyon/mmbot](https://hub.docker.com/r/celforyon/mmbot)) which is directly using mmpy_bot without any changes.
My `docker-compose.yml` file is:
```yaml
version: '2'     
services:
  mmbot:
    container_name: mmbot
    image: celforyon/mmbot
    network_mode: bridge
    restart: always
    environment:
    - MATTERMOST_DOMAIN=#censored url#
    - MATTERMOST_BOT_LOGIN=testbot
    - MATTERMOST_BOT_TOKEN=#censored token#
    - MATTERMOST_BOT_TEAM=Home
    - MATTERMOST_BOT_PLUGINS_ONLY_DOC=True
    volumes:
    - #censored path#:/plugins
    - #censored path#:/data
```
The token has been given by Mattermost right after creating the bot account.

Then, as I explained in my first message, it works with direct messages.
If you want, I can setup a server for you to test my configuration. Tell me if you are interested.
